#!/bin/bash

export DISPLAY=:0

JAVA=`which java`
WORKPATH="/vagrant/assets"
SELENIUM="${WORKPATH}/selenium-server-standalone-2.45.0.jar"
PROFILE="${WORKPATH}/firefox-profile"
PIDFILE="/tmp/selenium-server.pid"
LOGFILE="/var/log/selenium-server.log"
JAVAARGS="-jar ${SELENIUM} -timeout 180000 -trustAllSSLCertificates -firefoxProfileTemplate ${PROFILE} -log ${LOGFILE}"

case "$1" in
  start)
    echo -ne "Starting Selenium Server: "
    start-stop-daemon --start --quiet \
                      --background \
                      --pidfile $PIDFILE --make-pidfile \
                      --exec $JAVA \
                      -- $JAVAARGS
    echo " ....OK"
    ;;
  stop)
    echo -ne "Stopping Selenium Server: "
    start-stop-daemon --stop --quiet \
                      --pidfile $PIDFILE
    echo " ....OK"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  *)
    echo "Usage: selenium-server {start|stop|restart}"
    exit 1
esac

exit 0
